# For Fleet Free, this file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium, the default.yml file updates policies and queries that run on all hosts ("All teams"). Controls and agent options are updated for hosts on "No team."
policies:
  - path: ./lib/macos/policies/macos-cis.policies.yml
  - path: ./lib/macos/policies/macos-device-health.policies.yml

  - path: ./lib/windows/policies/windows-cis.policies.yml
  - path: ./lib/windows/policies/windows-device-health.policies.yml

  - path: ./lib/linux/policies/linux-device-health.policies.yml

queries:
agent_options:
  path: ./lib/agent-options.yml
controls:
  macos_settings:
    custom_settings:
      - path: ./lib/macos/profiles/macos-date-time.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-bluetooth-file-sharing.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-content-caching.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-guest-account.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-guest-shares.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-internet-sharing.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-media-sharing.mobileconfig
      - path: ./lib/macos/profiles/macos-disable-safari-safefiles.mobileconfig
      - path: ./lib/macos/profiles/macos-enable-doh.mobileconfig
      - path: ./lib/macos/profiles/macos-enable-firewall-logging.mobileconfig
      - path: ./lib/macos/profiles/macos-enable-gatekeeper.mobileconfig
      - path: ./lib/macos/profiles/macos-enforce-library-validation.mobileconfig
      - path: ./lib/macos/profiles/macos-firewall.mobileconfig
      - path: ./lib/macos/profiles/macos-full-disk-access-for-fleetd.mobileconfig
      - path: ./lib/macos/profiles/macos-limit-ad-tracking.mobileconfig
      - path: ./lib/macos/profiles/macos-misc.mobileconfig
      - path: ./lib/macos/profiles/macos-password.mobileconfig
      - path: ./lib/macos/profiles/macos-prevent-autologon.mobileconfig
      - path: ./lib/macos/profiles/macos-secure-terminal-keyboard.mobileconfig

#      - path: ./lib/macos/profiles/macos-chrome-enrollment.mobileconfig

#  windows_settings:
#    custom_settings:
#      - path: ./lib/windows/profiles/windows-firewall.xml
#      - path: ./lib/windows/profiles/windows-password.xml
#      - path: ./lib/windows/profiles/windows-screen-lock.xml

  scripts:
#    - path: ../lib/collect-fleetd-logs.sh

    - path: ./lib/macos/scripts/macos-install-update-homebrew.sh
    - path: ./lib/macos/scripts/macos-see-automatic-enrollment-profile.sh
    - path: ./lib/macos/scripts/macos-remove-old-nudge.sh
    - path: ./lib/macos/scripts/macos-mdm-migration.sh
    - path: ./lib/macos/scripts/macos-system-maintenance.sh

    - path: ./lib/windows/scripts/windows-remove-fleetd.ps1
    - path: ./lib/windows/scripts/windows-turn-off-mdm.ps1
    - path: ./lib/windows/scripts/windows-install-bitdefender.ps1
    - path: ./lib/windows/scripts/windows-enable-ms-defender.ps1

org_settings:
  features:
    enable_host_users: true
    enable_software_inventory: true
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Fleet
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"

software:
  app_store_apps:
    - app_store_id: '803453959' # Slack Desktop
    - app_store_id: '1477376905' # GitHub
    - app_store_id: '1152747299' # Figma