# For Fleet Free, this file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium, the default.yml file updates policies and queries that run on all hosts ("All teams"). Controls and agent options are updated for hosts on "No team."
policies:
  - path: ./lib/macos/policies/macos-cis.policies.yml

  - path: ./lib/windows/policies/windows-cis.policies.yml

  - path: ./lib/linux/policies/disk-encryption-check.yml

queries:
agent_options:
  path: ./lib/all/agent-options/agent-options.yml
controls:
  macos_settings:
    custom_settings:
      - path: ./lib/macos/configuration-profiles/automatic-updates.mobileconfig
      - path: ./lib/macos/configuration-profiles/date-time.mobileconfig
      - path: ./lib/macos/configuration-profiles/disable-bluetooth-file-sharing.mobileconfig
      - path: ./lib/macos/configuration-profiles/disable-content-caching.mobileconfig
      - path: ./lib/macos/configuration-profiles/disable-guest-account.mobileconfig
      - path: ./lib/macos/configuration-profiles/disable-internet-sharing.mobileconfig
      - path: ./lib/macos/configuration-profiles/disable-media-sharing.mobileconfig
      - path: ./lib/macos/configuration-profiles/disable-safari-safefiles.mobileconfig
      - path: ./lib/macos/configuration-profiles/enable-doh.mobileconfig
      - path: ./lib/macos/configuration-profiles/enable-firewall-logging.mobileconfig
      - path: ./lib/macos/configuration-profiles/enable-gatekeeper.mobileconfig
      - path: ./lib/macos/configuration-profiles/enable-siri.mobileconfig
      - path: ./lib/macos/configuration-profiles/enforce-library-validation.mobileconfig
      - path: ./lib/macos/configuration-profiles/firewall.mobileconfig
      - path: ./lib/macos/configuration-profiles/full-disk-access-for-fleetd.mobileconfig
      - path: ./lib/macos/configuration-profiles/limit-ad-tracking.mobileconfig
      - path: ./lib/macos/configuration-profiles/misc.mobileconfig
      - path: ./lib/macos/configuration-profiles/password.mobileconfig
      - path: ./lib/macos/configuration-profiles/prevent-autologon.mobileconfig
      - path: ./lib/macos/configuration-profiles/secure-terminal-keyboard.mobileconfig

#  windows_settings:
#    custom_settings:
#      - path: ./lib/windows/profiles/windows-firewall.xml
#      - path: ./lib/windows/profiles/windows-password.xml
#      - path: ./lib/windows/profiles/windows-screen-lock.xml

  scripts:
#    - path: ../lib/collect-fleetd-logs.sh

    - path: ./lib/macos/scripts/macos-install-update-homebrew.sh
    - path: ./lib/macos/scripts/macos-see-automatic-enrollment-profile.sh
    - path: ./lib/macos/scripts/macos-remove-old-nudge.sh
    - path: ./lib/macos/scripts/macos-mdm-migration.sh
    - path: ./lib/macos/scripts/macos-system-maintenance.sh
    - path: ./lib/macos/scripts/macos-mics.sh
    - path: ./lib/macos/scripts/macos-os-update.sh
    - path: ./lib/windows/scripts/windows-remove-fleetd.ps1
    - path: ./lib/windows/scripts/windows-turn-off-mdm.ps1
    - path: ./lib/windows/scripts/windows-install-bitdefender.ps1
    - path: ./lib/windows/scripts/windows-enable-ms-defender.ps1

org_settings:
  features:
    enable_host_users: true
    enable_software_inventory: true
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Huru
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"

software:
  app_store_apps:
    - app_store_id: '803453959' # Slack Desktop
    - app_store_id: '1477376905' # GitHub
    - app_store_id: '1152747299' # Figma